### ISSUE TITLE
**R4.4** Clarify the definition and purpose of profiles in RPP

### ISSUE THREAD

**Issue by pawel-kow** [ietf-wg-rpp/rpp-requirements#15]
**R4.4** RPP MUST have mechanisms to define profiles to indicate:

- Required parts of the data model
- Mapping definition
- Functional subsets for compatibility.

>> //MWU: maybe better describe what a profile is and what it is not.

> //PK: this would be then already the protocol specification, not a requirement, wouldn't it?

I propose a following text:

**R4.4** RPP MUST have mechanisms to define profiles using unambiguous identifiers (e.g., unique names or codes) that clearly specify:

- The essential components of the data model that must be implemented
- A clear and precise mapping of data elements to ensure interoperability
- Defined functional subsets that enable compatibility across different implementations.

**Comment by pawel-kow** [comment]
Just thinking loud now (in solution space):
- say you have following extensions/components: rppContact-1.0.0, rppDomain-1.0.0, rppHost-1.0.0
- protocol itself would be likely also versioned: 1.0.0
- Profile rppDomains-1.0.0 would be a combination of all this information:
```yaml pseudocode
rppDomains:
  profile-version: 1.0.0
  rpp-version: 1.0.0
  extensions:
    - rppContact:
        ext-version: 1.0.0
    - rppDomain:
        ext-version: 1.0.0
    - rppHost:
        ext-version: 1.0.0
```
- say SIDN would add a generic extension rppContactVat-1.0.0 on top of rppDomains-1.0.0:
```yaml pseudocode
sidn:
  profile-version: 1.0.0
  rpp-version: 1.0.0
  profiles:
    - rppDomains:
        profile-version: 1.0.0
  extensions:
    - rppContactVat-1.0.0
```

So, in discovery the server would list all extensions and also all profiles it supports.

Client, when making request would put a header (TBD if separate one or a parameter of media type) to state a profile.
The server would do the same in responses. Media type might be a good way to solve solve content negotiation (so client can also state which profile of an answer would be acceptable).

Question only how verbose the profile would be. It can go as far as declaring obligatory fields and methods (which would be otherwise optional):

```yaml pseudocode
sidn-1.0.0:
  profile-version: 1.0.0
  rpp-version: 1.0.0
  profiles:
    - rppDomains:
        profile-version: 1.0.0
  extensions:
    - rppContactVat
        ext-version: 1.0.0
    - rppContact:
        ext-version: 1.0.0
        required-fields:
          - name
          - address
          - ...
        required-operations:
          - transfer
          - ...
```

draft-stepanek-jscontact-profiles goes even further to say that if you profile an object type, you should specify all fields - mandatory and optional in its entirety, not just optional->mandatory changes.
